### ISSUE TITLE
Adding to Github teams error

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/pipekit#17]
The Github team addition fires when someone is moved *from* `Deposit Paid` to `Fees Paid` and throws up an error in Slack

**Comment by sjmog** [comment]
@nikeshashar thank you for leaving an issue! Is this an issue in Pipekit itself, or (probably more likely) an application in which Pipekit is used? If the latter, please would you mind re-creating this ticket in that repo?

**Comment by danldb** [comment]
closing this as wrong application
