### ISSUE TITLE
Add Activities

### ISSUE THREAD

**Issue by roidriscoll** [makersacademy/pipekit#21]
As part of https://github.com/makersacademy/applications/issues/553

**Comment by rachelcdavies** [comment]
Remember to add some notes explaining what this ticket represents and put an estimate on it.

**Comment by roidriscoll** [comment]
During the investigatory coding phase of this ticket (which I am engaging in to better understand the problem and put an accurate estimate on) I uncovered an issue with the pluralisation of resources. I have added a ticket to clean this behaviour up before continuing.

**Comment by roidriscoll** [comment]
Finally managed to get this working as a spike. A big part of it was finding a way to update PipeKit to be more flexible - going to look at handling that more gracefully on ticket number #22. But next step is to TDD this.
